### ISSUE TITLE
Crash on Meizu 16th device

### ISSUE THREAD

**Issue by XcJKing** [sharish/ShimmerRecyclerView#49]
I faced with Crash on Meizu 16th device
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Matrix.set(android.graphics.Matrix)' on a null object reference
       at android.graphics.Shader.copyLocalMatrix(Shader.java:159)
       at android.graphics.LinearGradient.copy(LinearGradient.java:129)
       at android.graphics.ComposeShader.copy(ComposeShader.java:96)
       at android.graphics.Shader.mzReversalCopy(Shader.java:134)
       at com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:651)
       at com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:631)
       at android.view.RecordingCanvas.drawRect(RecordingCanvas.java:622)
       at io.supercharge.shimmerlayout.ShimmerLayout.drawShimmer(ShimmerLayout.java:261)
       at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDrawShimmer(ShimmerLayout.java:250)
       at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:106)
       at android.view.View.draw(View.java:19239)
       at android.view.View.updateDisplayListIfDirty(View.java:18180)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19239)
       at android.view.View.updateDisplayListIfDirty(View.java:18180)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18171)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.draw(View.java:19239)
       at android.view.View.updateDisplayListIfDirty(View.java:18180)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18171)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18171)
       at android.view.View.draw(View.java:18958)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
       at android.view.View.updateDisplayListIfDirty(View.java:18171)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
       at android.view.View.updateDisplayListIfDirty(View.java:18139)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:705)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:803)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3025)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2828)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1408)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6853)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
       at android.view.Choreographer.doFrame(Choreographer.java:726)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6707)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by xie438305665** [comment]
> I faced with Crash on Meizu 16th device
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Matrix.set(android.graphics.Matrix)' on a null object reference
> at android.graphics.Shader.copyLocalMatrix(Shader.java:159)
> at android.graphics.LinearGradient.copy(LinearGradient.java:129)
> at android.graphics.ComposeShader.copy(ComposeShader.java:96)
> at android.graphics.Shader.mzReversalCopy(Shader.java:134)
> at com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:651)
> at com.meizu.nightmode.MzNightModeManager.beforeDrawColor(MzNightModeManager.java:631)
> at android.view.RecordingCanvas.drawRect(RecordingCanvas.java:622)
> at io.supercharge.shimmerlayout.ShimmerLayout.drawShimmer(ShimmerLayout.java:261)
> at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDrawShimmer(ShimmerLayout.java:250)
> at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:106)
> at android.view.View.draw(View.java:19239)
> at android.view.View.updateDisplayListIfDirty(View.java:18180)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.draw(View.java:19239)
> at android.view.View.updateDisplayListIfDirty(View.java:18180)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.updateDisplayListIfDirty(View.java:18171)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.draw(View.java:19239)
> at android.view.View.updateDisplayListIfDirty(View.java:18180)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.updateDisplayListIfDirty(View.java:18171)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.updateDisplayListIfDirty(View.java:18171)
> at android.view.View.draw(View.java:18958)
> at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
> at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
> at android.view.View.updateDisplayListIfDirty(View.java:18171)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
> at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
> at android.view.View.updateDisplayListIfDirty(View.java:18139)
> at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:705)
> at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:803)
> at android.view.ViewRootImpl.draw(ViewRootImpl.java:3025)
> at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2828)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2375)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1408)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6853)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
> at android.view.Choreographer.doCallbacks(Choreographer.java:791)
> at android.view.Choreographer.doFrame(Choreographer.java:726)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6707)
> at java.lang.reflect.Method.invoke(Method.java)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

解決了？

**Comment by Tukesboy** [comment]
Has this problem been solved?

**Comment by Tukesboy** [comment]
这个问题有解决方案吗，求分享

**Comment by Tukesboy** [comment]
@sharish
